# action.yml
name: 'ARM-TTK'
description: 'runs arm-ttk as a part of a workflow'
inputs:
  path:
    required: true
    description: 'Path to run the tests on' 
  file:
    required: false
    description: 'Run the test on a specific file on the path defined'
  tests:
    required: false
    description: 'Test(s) to run, comma separated'
  skip:
    required: false
    description: 'Test(s) to be excluded, comma separated'
outputs:
  results:
    description: 'Test Results as a sting'
branding:
  icon: 'check-square'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.file }}
    - ${{ inputs.tests }}
    - ${{ inputs.skip }}
