# action.yml
name: 'ARM-TTK'
description: 'runs arm-ttk as a part of a workflow'
inputs:
  args:
    required: true
    description: 'arm-ttk args'
branding:
  icon: 'command'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'

