name: test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Run ARM-TTK on 'unit-tests' folder
      uses: ./
      with: 
        args: unit-tests
