name: test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - run: git clone https://github.com/Azure/azure-quickstart-templates.git

    - name: Run ARM-TTK for azure-quickstart-templates/101-storage-account-create/
      uses: ./
      with: 
        args: azure-quickstart-templates/101-storage-account-create/
